name: cotwcompanion
description: Companion for the game theHunter Call of the Wild

publish_to: 'none'

version: 1.10.1+84

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_xlider: ^3.0.2
  async: 2.11.0
  auto_size_text: 3.0.0
  blurrycontainer: 2.1.0
  collection: ^1.18.0
  device_info_plus: ^10.1.0
  easy_localization: ^3.0.7
  easy_rich_text: ^2.1.0
  equatable: 2.0.5
  file_picker: ^8.0.3
  fl_chart: 0.68.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_gen_runner: ^5.6.0
  flutter_lints: 4.0.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  latlng: 2.0.7
  logger: ^2.3.0
  map: 2.0.2
  omni_datetime_picker: ^2.0.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  simple_shadow: 0.3.1
  smooth_page_indicator: 1.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/generated/
  assets:
    exclude:
      - assets/fonts/*
      - assets/translations/*
      - assets/graphics/maps/**/*

flutter:
  uses-material-design: true
  assets:
    - assets/raw/
    - assets/raw/maps/
    - assets/fonts/
    - assets/translations/
    - assets/graphics/icons/
    - assets/graphics/images/
    - assets/graphics/animals/
    - assets/graphics/reserves/
    - assets/graphics/weapons/
    - assets/graphics/callers/
    - assets/graphics/anatomy/
    - assets/graphics/heads/
    - assets/graphics/proficiency/
    - assets/graphics/maps/hirschfeldenhuntingreserve/1/
    - assets/graphics/maps/hirschfeldenhuntingreserve/2/
    - assets/graphics/maps/hirschfeldenhuntingreserve/3/
    - assets/graphics/maps/laytonlakedistrict/1/
    - assets/graphics/maps/laytonlakedistrict/2/
    - assets/graphics/maps/laytonlakedistrict/3/
    - assets/graphics/maps/medvedtaiganationalpark/1/
    - assets/graphics/maps/medvedtaiganationalpark/2/
    - assets/graphics/maps/medvedtaiganationalpark/3/
    - assets/graphics/maps/vurhongasavannareserve/1/
    - assets/graphics/maps/vurhongasavannareserve/2/
    - assets/graphics/maps/vurhongasavannareserve/3/
    - assets/graphics/maps/parquefernando/1/
    - assets/graphics/maps/parquefernando/2/
    - assets/graphics/maps/parquefernando/3/
    - assets/graphics/maps/yukonvalley/1/
    - assets/graphics/maps/yukonvalley/2/
    - assets/graphics/maps/yukonvalley/3/
    - assets/graphics/maps/cuatrocolinasgamereserve/1/
    - assets/graphics/maps/cuatrocolinasgamereserve/2/
    - assets/graphics/maps/cuatrocolinasgamereserve/3/
    - assets/graphics/maps/silverridgepeaks/1/
    - assets/graphics/maps/silverridgepeaks/2/
    - assets/graphics/maps/silverridgepeaks/3/
    - assets/graphics/maps/teawaroanationalpark/1/
    - assets/graphics/maps/teawaroanationalpark/2/
    - assets/graphics/maps/teawaroanationalpark/3/
    - assets/graphics/maps/ranchodelarroyo/1/
    - assets/graphics/maps/ranchodelarroyo/2/
    - assets/graphics/maps/ranchodelarroyo/3/
    - assets/graphics/maps/mississippiacrespreserve/1/
    - assets/graphics/maps/mississippiacrespreserve/2/
    - assets/graphics/maps/mississippiacrespreserve/3/
    - assets/graphics/maps/revontulicoast/1/
    - assets/graphics/maps/revontulicoast/2/
    - assets/graphics/maps/revontulicoast/3/
    - assets/graphics/maps/newenglandmountains/1/
    - assets/graphics/maps/newenglandmountains/2/
    - assets/graphics/maps/newenglandmountains/3/
    - assets/graphics/maps/emeraldcoastaustralia/1/
    - assets/graphics/maps/emeraldcoastaustralia/2/
    - assets/graphics/maps/emeraldcoastaustralia/3/
    - assets/graphics/maps/sundarpatanhuntingreserve/1/
    - assets/graphics/maps/sundarpatanhuntingreserve/2/
    - assets/graphics/maps/sundarpatanhuntingreserve/3/
  fonts:
    - family: Normal
      fonts:
        - asset: assets/fonts/Normal200.ttf
          weight: 200
        - asset: assets/fonts/Normal300.ttf
          weight: 300
        - asset: assets/fonts/Normal400.ttf
          weight: 400
        - asset: assets/fonts/Normal500.ttf
          weight: 500
        - asset: assets/fonts/Normal600.ttf
          weight: 600
        - asset: assets/fonts/Normal700.ttf
          weight: 700
    - family: Condensed
      fonts:
        - asset: assets/fonts/Condensed300.ttf
          weight: 300
        - asset: assets/fonts/Condensed400.ttf
          weight: 400
        - asset: assets/fonts/Condensed600.ttf
          weight: 600